# Generated by Django 4.2.19 on 2025-03-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
    ]
