# Generated by Django 4.2.19 on 2025-03-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20250304_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='geojson_data',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
