# Generated by Django 4.2.19 on 2025-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_country_geojson_data_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='te', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
