# Generated by Django 4.2.19 on 2025-03-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_country_currency_name_country_currency_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='gini_index',
        ),
    ]
